#+TITLE: Preguntas Frecuentes

#+AUTHOR: Escuela Técnica Superior de Ingeniería y Diseño Industrial {{{NEWLINE}}} Universidad Politécnica de Madrid

#+DATE: 

#+SETUPFILE: config.org

#+TOC: headlines 2


* General
  :PROPERTIES:
  :CUSTOM_ID: general
  :END:
** ¿Qué es un ECTS?
ECTS es la sigla correspondiente a European Credit Transfer System (Sistema Europeo de Transferencia de Créditos). Es el estándar adoptado por todas las universidades del Espacio Europeo de Educación Superior (EEES) para garantizar la homogeneidad y la calidad de los estudios que ofrecen. El ECTS se basa en la convención de que 60 créditos miden la *carga de trabajo de un estudiante* a tiempo completo durante un curso académico. En el caso de la Universidad Politécnica se emplea una correspondencia de 26 o 27 horas por 1 ECTS, incluyendo las horas de clase teóricas y practicas, las horas de estudio, seminarios, realización de trabajos individuales o en grupo, de prácticas o proyectos, resolución de ejercicios, búsqueda de información, prácticas, exámenes, etc. 

Un grado se conforman con 240 ECTS en 4 años de 60 ECTS (8 semestres de 30 ECTS). Por tanto, un alumno de grado tendrá una carga de trabajo estimada en 1620 horas anuales. 

En la ETSIDI, en términos generales, se asignan a cada asignatura 10 horas lectivas por cada ECTS. De esta forma, una asignatura de 4.5 ECTS tendrá 45 horas totales de docencia presencial (3 horas por semana considerando un semestre de genérico de 15 semanas lectivas).

El ECTS también se puede emplear para cuantificar la dedicación docente del profesor, tal y como hace el [[http://www.upm.es/sfs/SedeUPM/Normativa%2520UPM/Actividad%2520Docente.pdf][Modelo de Estimación de la Actividad de los Departamentos de la Universidad Politécnica de Madrid]], que contabiliza una actividad lectiva presencial del profesor de entre 8 a 12 horas por cada ECTS.

** ¿Qué significa la evaluación continua?
** ¿Dónde está el calendario de la ETSIDI?
   :PROPERTIES:
   :CUSTOM_ID: calendario
   :END:

El calendario de la ETSIDI está disponible en PDF en diferentes formatos en este enlace: 

http://www.etsidi.upm.es/Estudiantes/AgendaAcademica/AACalendario.

Está también disponible en formato [[https://es.wikipedia.org/wiki/ICalendar][iCalendar]] para que lo añadas a tu aplicación de calendario: [[http://programas.etsidi.upm.es/webdav/cal/ETSIDI_Grado.ics][Grado]] y [[http://programas.etsidi.upm.es/webdav/cal/ETSIDI_Master.ics][Máster]].

** ¿Dónde puedo obtener los horarios de clase?
   :PROPERTIES:
   :CUSTOM_ID: horarios
   :END:

Los horarios de clase están disponibles en este enlace: 

http://www.etsidi.upm.es/Estudiantes/AgendaAcademica/AAHorarioClases

Como se indica en esta página, existe un buscador que te permite obtener toda la información de horarios, profesorado y aulas con flexibilidad: 

http://programas.etsidi.upm.es/SOA/buscador/

** ¿Dónde está el calendario de exámenes finales?
   :PROPERTIES:
   :CUSTOM_ID: examenes
   :END:

El calendario de exámenes finales está disponible en este enlace: 

http://programas.etsidi.upm.es/webdav/cal/examenes.html. 

También está en formato PDF en este enlace: 

http://www.etsidi.upm.es/Estudiantes/AgendaAcademica/AAFechaExamenes

** ¿Qué significan los códigos numéricos de cada asignatura?
   :PROPERTIES:
   :CUSTOM_ID: codigos
   :END:

Cada asignatura de la UPM tiene un código único que sirve para identificar la Escuela y, en general, la titulación. Las dos primeras cifras son propias de la Escuela, y a la ETSIDI le corresponde el número 56. En la ETSIDI, la siguiente cifra indica si se trata de un grado (5) o un máster (3). En el caso de los grados, las últimas tres cifras indican la titulación y el semestre. La correspondencia entre titulación y cifra es la siguiente:

- Ing. Electrónica Industrial y Automática - IA - 1
- Ing. Eléctrica - IE - 2
- Ing. Mecánica - IM - 3
- Ing. Química - IQ - 4
- Ing. en Diseño Industrial y Desarrollo de Producto - DD - 5

Por ejemplo, el código 565000424 indica que es una asignatura de la ETSIDI (56) del grado (5) IQ (4) impartida en el segundo semestre (2). 

** ¿Dónde están las Guías de la Asignatura?
   :PROPERTIES:
   :CUSTOM_ID: ga
   :END:

Las Guías de Asignatura (GAs) están disponibles en la página dedicada a cada titulación ([[http://www.etsidi.upm.es/Estudiantes/EstudiosTitulaciones/ETTitulosGrado/ETTitulosOficialesGrado][Grado]] y [[http://www.etsidi.upm.es/Estudiantes/EstudiosTitulaciones/ETTitulosPostgrado/ETTitulosOficialesMaster][Máster]]).

Todos los PDFs de las GAs están accesibles en esta URL: https://www.upm.es/comun_gauss/publico/guias. Cada Guía de Asignatura tiene su propia URL, que se construye a partir de su código: 

#+BEGIN_EXAMPLE
[CURSO]/[SEMESTRE]S/GA_56[CODIGO_TITULACION]_[CODIGO_ASIGNATURA]_[SEMESTRE]S_[CURSO].pdf
#+END_EXAMPLE


Utilizando el ejemplo anterior, la guía del curso 2017-18 de la asignatura 565000424 (grado IQ, segundo semestre) está disponible en:

https://www.upm.es/comun_gauss/publico/guias/2017-18/2S/GA_56IQ_565000424_2S_2017-18.pdf

** Quisiera conocer el histórico de los resultados agregados de una asignatura. ¿Dónde puedo consultarlos?
   :PROPERTIES:
   :CUSTOM_ID: ia
   :END:

Los anexos de los informes de asignatura (IA) contienen los resultados de los últimos cursos. Están disponibles en una URL similar a la de la GA correspondiente. La dirección raíz es https://www.upm.es/comun_gauss/publico/anexos_IA/, y la estructura es:

#+BEGIN_EXAMPLE
[CURSO]/[SEMESTRE]S/IA_anexos_56[CODIGO_TITULACION]_[CODIGO_ASIGNATURA]_[SEMESTRE]S_[CURSO]_1.pdf
#+END_EXAMPLE

Continuando con el ejemplo anterior:

https://www.upm.es/comun_gauss/publico/anexos_IA/2016-17/2S/IA_anexos_56IQ_565000424_2S_2016-17_1.pdf


* Profesores
  :PROPERTIES:
  :CUSTOM_ID: profesores
  :END:

** Necesito reservar un espacio para actividades docentes. ¿Cómo lo hago?
   :PROPERTIES:
   :CUSTOM_ID: aulas
   :END:

Primero debes consultar la asignación docente de aulas y las reservas existentes en el calendario publicado en la siguiente web:

http://programas.etsidi.upm.es/webdav/aulas/

A continuación, debes ponerte en contacto con la secretaría de Jefatura de Estudios para hacer la reserva que corresponda. Podrás comprobar el resultado en el calendario anterior.

** Quiero proponer un Trabajo de Fin de de Grado. ¿Qué debo hacer?
   :PROPERTIES:
   :CUSTOM_ID: tfg_profesor
   :END:

Para hacer una propuesta de TFG debes rellenar el formulario disponible en la siguiente web, empleando tu usuario y contraseña de UPM:

https://documentos.etsidi.upm.es/tfgs/login

Las propuestas pueden ser Generales (TFG para ser desarrollado individualmente por un número indeterminado de estudiantes, en una o varias convocatorias) o Específicas (la temática a desarrollar se limita a un único TFG para un alumno).

La propuesta será informada por el coordinador de TFG de la titulación que corresponda. Además, este coordinador asignará el tercer miembro del tribunal. A continuación, la propuesta será revisada y, en su caso, confirmada por el Director de Departamento. Todas las propuestas realizadas son revisadas en una reunión mensual de la Comisión Académica de TFG, compuesta por los cinco coordinadores de TFG y el Jefe de Estudios. Como resultado de esta reunión, se validan y publican las propuestas que no necesitan ninguna corrección. A partir de este momento, la propuesta está visible para los alumnos en la misma aplicación.

*No olvides consultar la [[http://www.etsidi.upm.es/sfs/E.U.I.T.%2520Industrial/SECRETARIA%2520DE%2520ALUMNOS/ARTICULOS/Normativa%2520TFG.pdf][normativa de TFG de la ETSIDI]]*.


** Quiero proponer un Trabajo de Fin de de Máster. ¿Qué debo hacer?
   :PROPERTIES:
   :CUSTOM_ID: tfm_profesor
   :END:

Para hacer una propuesta de TFG debes rellenar el formulario disponible en la siguiente web, empleando tu usuario y contraseña de UPM:

https://documentos.etsidi.upm.es/tfms/login


*No olvides consultar la [[http://www.etsidi.upm.es/sfs/E.U.I.T.%2520Industrial/SECRETARIA%2520DE%2520ALUMNOS/ARTICULOS/Normativa%2520TFG.pdf][normativa de TFM de la ETSIDI]]*.


* Alumnos
  :PROPERTIES:
  :CUSTOM_ID: alumnos
  :END:

** Prefiero realizar la evaluación mediante examen final. ¿Qué debo hacer?
** ¿Cómo puedo saber los horarios de tutoría de un profesor?
   :PROPERTIES:
   :CUSTOM_ID: tutorias
   :END:

Los horarios de tutoría del profesorado están disponibles en esta web:

http://programas.etsidi.upm.es/SOA/tutorias/

** No he podido asistir a un examen. ¿Qué puedo hacer? 
   :PROPERTIES:
   :CUSTOM_ID: art24_alumno
   :END:

En primer lugar, debe tratarse de una causa de fuerza mayor o asistencia a reuniones por representación estudiantil. En segundo lugar, la causa debe justificarse fehacientemente (certificado médico, etc.).

Si se cumplen estas dos condiciones, debes dirigirte al coordinador de la asignatura si se trata de una prueba de evaluación continua, o al Jefe de Estudios en el caso de una prueba de evaluación final.

Debes consultar lo indicado en el "Artículo 24. De los estudiantes que no puedan realizar el examen en la fecha prevista" de la [[http://www.upm.es/sfs/Rectorado/Vicerrectorado%2520de%2520Alumnos/Informacion/Normativa/2017_18_NormativadeEvaluacion_CG%2520170525.pdf][normativa de evaluación de la UPM]].

** Quiero comenzar a realizar el Trabajo de Fin de Grado. ¿Qué debo hacer?
   :PROPERTIES:
   :CUSTOM_ID: tfg_alumno
   :END:

https://documentos.etsidi.upm.es/tfgs/login

** Quiero comenzar a realizar el Trabajo de Fin de Máster. ¿Qué debo hacer?
   :PROPERTIES:
   :CUSTOM_ID: tfm_alumno
   :END:

https://documentos.etsidi.upm.es/tfms/login

** Quiero defender mi TFG en la próxima convocatoria. ¿Qué debo hacer?

Debes cumplir dos condiciones:

- El tutor del TFG debe dar el visto bueno a la finalización del TFG.
- D
** Soy futuro alumno de Máster, y tengo muchas dudas.

http://www.upm.es/Estudiantes/Estudios_Titulaciones/Estudios_Master/preguntas_frecuentes
